services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./.env:/var/www/html/.env
    environment:
      - APP_ENV=local
      - NODE_ENV=development
    networks:
      - laravel
    ports:
      - "9000:9000"
    depends_on:
      - db
  web:
    image: nginx:latest
    container_name: nginx-web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    networks:
      - laravel
    ports:
      - "8000:80"
    depends_on:
      - app
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel
    ports:
      - "3308:3308"
    volumes:
      - db_data:/var/lib/mysql
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    networks:
      - laravel
    ports:
      - "3000:3000"
    command: npm run dev

networks:
  laravel:

volumes:
  db_data:
