# Dockerfile.vite
FROM node:20

WORKDIR /var/www/html

COPY package*.json ./

RUN npm install
RUN npm install -g jest && npm install jest-environment-jsdom

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
